#!/bin/sh

# GH CHECK
# Run command, always return success for GitHub action!
# Allows us to capture artifacts and test for success later

echo "CHECK: ${*}"

# Adds gh/ to PATH to shorten commands

if [ ! -d gh ]
then
  echo "CHECK: MISCONFIGURATION!"
  exit 1
fi

PATH=$PWD/gh:$PATH

set -x
echo "CHECK: PWD: $PWD"
echo "CHECK: LS:"
ls -a
ls -a tests

# Run the arguments here!
if ${*}
then
  echo "CHECK: OK."
else
  echo "CHECK: FAILED: ${*}"
fi
