name: Test from Clone
on: [push, pull_request, workflow_dispatch]
jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11" "3.12"]
        os: [ubuntu-latest, macOS-latest]
        # There is no free mac-14 for x86 on GitHub
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          # auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Check environment
        run: |
          echo "hostname:" $(hostname)
          echo "whoami:  " $(whoami)
          echo "date:    " $(date "+%Y-%m-%d %H:%M")
          echo "pwd:     " $(pwd -P)
          # Conda has not been activated- this will change in install_emews.sh
          echo "python:  " $(which python)
          echo
          git log -n 1 --date="format:%Y-%m-%d %H:%m" --format=tformat:"%h %cd %an : %s"
          echo
      - name: Set up GitHub PAT
        # Set up PAT for R install_github()
        run: |
          echo "GITHUB_PAT=${{ secrets.GH_PAT_WOZ }}" >> ~/.Renviron
      - name: Install EMEWS
        # Build with quiet, tests, and verbose
        run: |
          gh/check code/install/install_emews.sh -q -t -v ${{ matrix.python-version }} $PWD/DB
      - name: Inspect installation
        run: |
          gh/inspect-install.sh code/install/emews_install.log
      - name: Test Swift/T
        run: |
          gh/check tests/test-swift-t.sh ${{ matrix.python-version }}
      - name: Inspect tests
        run: |
          gh/inspect-tests.sh
