name: Test from Curl
on: [push, pull_request, workflow_dispatch]
jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10"]
          # ["3.8", "3.9", "3.10", "3.11", "3.12"]
        os: [ubuntu-latest, macOS-latest]
        # There is no free mac-14 for x86 on GitHub
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          # auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Check environment
        run: |
          echo "hostname:" $(hostname)
          echo "whoami:  " $(whoami)
          echo "date:    " $(date "+%Y-%m-%d %H:%M")
          echo "pwd:     " $(pwd -P)
          # Conda has not been activated- this will change in install_emews.sh
          echo "python:  " $(which python)
          echo
      - name: Download scripts
        run: |
          # -L : location redirect
          # -O : remote-name
          # -s : silent
          # -S : show-error
          curl -LOsS https://raw.githubusercontent.com/emews/emews-tutorial/main/code/install/install_emews.sh
          curl -LOsS https://raw.githubusercontent.com/emews/emews-tutorial/main/code/install/install_pkgs.R
      - name: Set up GitHub PAT
        # Set up PAT for R install_github()
        run: |
          echo "GITHUB_PAT=${{ secrets.GH_PAT_WOZ }}" >> ~/.Renviron
      - name: Install EMEWS
        run: |
          bash install_emews.sh ${{ matrix.python-version }} $PWD/DB
      - name: Inspect installation
        run: |
          # Look for SUCCESS in log:
          grep "INSTALL SUCCESS." emews_install.log
      - name: Runtime tests
        run: |
          ./gh-run echo gh-run works
          ./gh-run swift-t -v
          ./gh-run swift-t -E 'trace("SUCCESS: SWIFT/T");'
          ./gh-run swift-t -i EQR -E 'trace("SUCCESS: EQ/R   ");'


# TODO: Needs -I $CONDA_PREFIX/lib

# We do not test everything here because we don't have a full clone.
# See ./test-clone.yaml for the Swift/T tests.
